In [21]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn import svm
from sklearn import tree
from sklearn.metrics import precision_recall_fscore_support
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
trainfile = "trainSet.csv"
testfile = "testSet.csv"
df = pd.read_csv(trainfile)
tdf = pd.read_csv(testfile)
n_splits = 10
skf = StratifiedKFold(n_splits, random_state=1)
del df['input']
del tdf['input']
del df['length']
del tdf['length']


#Getting the Test and Train data
#Doing a 10 fold split using StratifiedKFold

In [22]:
y_col = 'person'
target = df[y_col].values
test_target = tdf[y_col].values
del df[y_col]
del tdf[y_col]
train_data = df.values
test_data = tdf.values
skf.get_n_splits(df, target)

10

#Training Data:

In [23]:
print(train_data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#Train_Label_data

In [24]:
target

array([0, 0, 0, ..., 0, 0, 0])

#Decision Tree Classfier

In [25]:
decisiontree_classifier = tree.DecisionTreeClassifier()
precision_list = []
recall_list = []
fscore_list = []
for train_index, test_index in skf.split(train_data, target):
    decisiontree_classifier.fit(train_data[train_index],target[train_index])
    y_pred = decisiontree_classifier.predict(train_data[test_index])
    precision,recall,fscore,support = precision_recall_fscore_support(target[test_index], y_pred, average='macro')
    precision_list.append(precision)
    recall_list.append(recall)
    fscore_list.append(fscore)
print("\n\nMax Precision: "+ str(max(precision_list))+ "\nMax Recall: " + str(max(recall_list))+ "\nMax fscore: "+ str(max(fscore_list)))



Max Precision: 0.8312406994047619
Max Recall: 0.8621185618608299
Max fscore: 0.8442616474962239


#Linear SVM:

In [30]:
svm_clf = svm.SVC(kernel = 'rbf', random_state = 1, gamma = 0.1, C = 10.0)
precision_list = []
recall_list = []
fscore_list = []
for train_index, test_index in skf.split(train_data, target):
    svm_clf.fit(train_data[train_index],target[train_index])
    y_pred = svm_clf.predict(train_data[test_index])
    precision,recall,fscore,support = precision_recall_fscore_support(target[test_index], y_pred, average='macro')
    precision_list.append(precision)
    recall_list.append(recall)
    fscore_list.append(fscore)
print("\n\nMax Precision: " + str(max(precision_list)) + "\nMax Recall: " + str(max(recall_list)) + "\nMax fscore: " + str(max(fscore_list)))



Max Precision: 0.8253543753998297
Max Recall: 0.8633502981843093
Max fscore: 0.8367763039971321


#Linear Regression

In [26]:
linreg = LinearRegression()
precision_list = []
recall_list = []
fscore_list = []
for train_index, test_index in skf.split(train_data, target):
    linreg.fit(train_data[train_index],target[train_index])
    y_pred = linreg.predict(train_data[test_index])
    thresh = round(np.mean(y_pred), 2)
    y_pred = np.where(y_pred > thresh, 1, 0)
    precision,recall,fscore,support = precision_recall_fscore_support(target[test_index], y_pred, average='macro')
    precision_list.append(precision)
    recall_list.append(recall)
    fscore_list.append(fscore)
print("\n\nMax Precision: " + str(max(precision_list)) + "\nMax Recall: " + str(max(recall_list)) + "\nMax fscore: " + str(max(fscore_list)))




Max Precision: 0.5505575400920302
Max Recall: 0.905797970884358
Max fscore: 0.5589782809606824


#Logistic Regresssion

In [20]:
logreg = LogisticRegression(C = 100.0, random_state = 1)
precision_list = []
recall_list = []
fscore_list = []
for train_index, test_index in skf.split(train_data, target):
    logreg.fit(train_data[train_index],target[train_index])
    y_pred = logreg.predict(train_data[test_index])
    precision,recall,fscore,support = precision_recall_fscore_support(target[test_index], y_pred, average='macro')
    precision_list.append(precision)
    recall_list.append(recall)
    fscore_list.append(fscore)
print("\n\nMax Precision: " + str(max(precision_list)) + "\nMax Recall: " + str(max(recall_list)) + "\nMax fscore: " + str(max(fscore_list)))



Max Precision: 0.9276828371922088
Max Recall: 0.6506795739274696
Max fscore: 0.7148101250898973


#Random Forest

In [28]:
randomforest = RandomForestClassifier(random_state=1)
precision_list = []
recall_list = []
fscore_list = []
for train_index, test_index in skf.split(train_data, target):
    randomforest.fit(train_data[train_index],target[train_index])
    y_pred = randomforest.predict(train_data[test_index])
    precision,recall,fscore,support = precision_recall_fscore_support(target[test_index], y_pred, average='macro')
    precision_list.append(precision)
    recall_list.append(recall)
    fscore_list.append(fscore)
print("\n\nMax Precision: " + str(max(precision_list)) + "\nMax Recall: " + str(max(recall_list)) + "\nMax fscore: " + str(max(fscore_list)))



Max Precision: 0.8317550079317675
Max Recall: 0.8621882191469821
Max fscore: 0.8291422052286799


#Best Classifier was Logistic Regression 

#Running Logistic Regression on TestSet

In [29]:
logreg = LogisticRegression(C = 100.0, random_state=1)
logreg.fit(train_data, target)
y_pred = logreg.predict(test_data)
precision, recall, fscore ,support = precision_recall_fscore_support(test_target, y_pred, average='macro')
print("Precision on Test Set: "+ str(precision) +
      "\nRecall on Test Set: "+ str(recall) +
      "\nFScore on Test Set: "+ str(fscore))

Precision on Test Set: 0.9193543846640266
Recall on Test Set: 0.6398560040653727
FScore on Test Set: 0.7080104161812235
